import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { extname, relative, resolve, sep } from "node:path";

const root = resolve("dist");
const output = resolve("server/prisma-assets.ts");
const mimeTypes: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".webmanifest": "application/manifest+json",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".otf": "font/otf",
  ".txt": "text/plain; charset=utf-8",
  ".wasm": "application/wasm",
};

function walk(dir: string): string[] {
  const files: string[] = [];
  for (const name of readdirSync(dir)) {
    const full = resolve(dir, name);
    const stat = statSync(full);
    if (stat.isDirectory()) files.push(...walk(full));
    else if (stat.isFile() && name !== "server.mjs" && !name.endsWith(".map")) files.push(full);
  }
  return files;
}

const assets: Record<string, { contentType: string; base64: string }> = {};
for (const file of walk(root)) {
  const rel = relative(root, file).split(sep).join("/");
  assets["/" + rel] = {
    contentType: mimeTypes[extname(file).toLowerCase()] ?? "application/octet-stream",
    base64: readFileSync(file).toString("base64"),
  };
}
if (!assets["/index.html"]) throw new Error("Vite build did not produce dist/index.html");
writeFileSync(
  output,
  "// Generated by scripts/prisma-assets.ts during the build. Do not edit by hand.\n" +
    "export const PRISMA_ASSETS: Record<string, { contentType: string; base64: string }> = " +
    JSON.stringify(assets) +
    ";\n",
);
const totalBytes = Object.values(assets).reduce((sum, item) => sum + Buffer.from(item.base64, "base64").byteLength, 0);
console.log(`[prisma-build] embedded ${Object.keys(assets).length} frontend files (${totalBytes} bytes)`);
